package com.zhangqiang.web.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zhangqiang.web.db.entity.BookMarkEntity;
import com.zhangqiang.web.db.entity.VisitRecordEntity;

import com.zhangqiang.web.db.dao.BookMarkEntityDao;
import com.zhangqiang.web.db.dao.VisitRecordEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookMarkEntityDaoConfig;
    private final DaoConfig visitRecordEntityDaoConfig;

    private final BookMarkEntityDao bookMarkEntityDao;
    private final VisitRecordEntityDao visitRecordEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookMarkEntityDaoConfig = daoConfigMap.get(BookMarkEntityDao.class).clone();
        bookMarkEntityDaoConfig.initIdentityScope(type);

        visitRecordEntityDaoConfig = daoConfigMap.get(VisitRecordEntityDao.class).clone();
        visitRecordEntityDaoConfig.initIdentityScope(type);

        bookMarkEntityDao = new BookMarkEntityDao(bookMarkEntityDaoConfig, this);
        visitRecordEntityDao = new VisitRecordEntityDao(visitRecordEntityDaoConfig, this);

        registerDao(BookMarkEntity.class, bookMarkEntityDao);
        registerDao(VisitRecordEntity.class, visitRecordEntityDao);
    }
    
    public void clear() {
        bookMarkEntityDaoConfig.clearIdentityScope();
        visitRecordEntityDaoConfig.clearIdentityScope();
    }

    public BookMarkEntityDao getBookMarkEntityDao() {
        return bookMarkEntityDao;
    }

    public VisitRecordEntityDao getVisitRecordEntityDao() {
        return visitRecordEntityDao;
    }

}
