package com.zhangqiang.web.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zhangqiang.web.db.entity.VisitRecordEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VISIT_RECORD_ENTITY".
*/
public class VisitRecordEntityDao extends AbstractDao<VisitRecordEntity, String> {

    public static final String TABLENAME = "VISIT_RECORD_ENTITY";

    /**
     * Properties of entity VisitRecordEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property IconUrl = new Property(1, String.class, "iconUrl", false, "ICON_URL");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property Url = new Property(3, String.class, "url", false, "URL");
        public final static Property VisitDate = new Property(4, long.class, "visitDate", false, "VISIT_DATE");
    }


    public VisitRecordEntityDao(DaoConfig config) {
        super(config);
    }
    
    public VisitRecordEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VISIT_RECORD_ENTITY\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"ICON_URL\" TEXT," + // 1: iconUrl
                "\"TITLE\" TEXT," + // 2: title
                "\"URL\" TEXT NOT NULL ," + // 3: url
                "\"VISIT_DATE\" INTEGER NOT NULL );"); // 4: visitDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VISIT_RECORD_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, VisitRecordEntity entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String iconUrl = entity.getIconUrl();
        if (iconUrl != null) {
            stmt.bindString(2, iconUrl);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
        stmt.bindString(4, entity.getUrl());
        stmt.bindLong(5, entity.getVisitDate());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, VisitRecordEntity entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String iconUrl = entity.getIconUrl();
        if (iconUrl != null) {
            stmt.bindString(2, iconUrl);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
        stmt.bindString(4, entity.getUrl());
        stmt.bindLong(5, entity.getVisitDate());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public VisitRecordEntity readEntity(Cursor cursor, int offset) {
        VisitRecordEntity entity = new VisitRecordEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // iconUrl
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
            cursor.getString(offset + 3), // url
            cursor.getLong(offset + 4) // visitDate
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, VisitRecordEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setIconUrl(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUrl(cursor.getString(offset + 3));
        entity.setVisitDate(cursor.getLong(offset + 4));
     }
    
    @Override
    protected final String updateKeyAfterInsert(VisitRecordEntity entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(VisitRecordEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(VisitRecordEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
